version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: creditdb
      POSTGRES_USER: credit
      POSTGRES_PASSWORD: creditpass
      DB_HOST: db
      DB_PORT: '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
  web:
    build: .
    entrypoint: ["/app/entrypoint.sh"]   # 👈 use entrypoint.sh
    volumes:
      - .:/app
      - ./data:/data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://credit:creditpass@db:5432/creditdb
  worker:
    build: .
    command: >
      sh -c "celery -A credit_system worker --loglevel=info"
    volumes:
      - .:/app
      - ./data:/data
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
